# .github/workflows/release.yml
name: 🏷️ Cut Release

on:
  workflow_dispatch:
    inputs:
      level:
        description: 'Release level: major, minor, or patch'
        required: true
        default: 'patch'

permissions:
  contents: write

jobs:
  bump-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout all history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install bump2version
        run: pip install bump2version

      - name: Bump version & create tag
        env:
          BUMPLEVEL: ${{ github.event.inputs.level }}
        run: |
          bump2version --allow-dirty ${BUMPLEVEL}  # e.g. 'patch', 'minor', 'major'

      - name: Push commit + tag
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin \
            https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git
          git push origin HEAD:main --follow-tags
