# .github/workflows/ci-deploy.yml
name: CI • Build, Tag, Push & Deploy

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: jhunter7/jhdev

jobs:
  version:
    name: Bump Version with bump2version
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.bump.outputs.new_version }}
    steps:
      - name: Check out full history & tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Configure Git identity
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "actions@github.com"

      - name: Install bump2version
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install bump2version

      - id: bump
        name: Sync & bump patch version
        run: |
          # 1) Ensure VERSION file matches latest Git tag
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "Latest Git tag is $LATEST_TAG"
          echo "${LATEST_TAG#v}" > VERSION
          git add VERSION

          # 2) Bump patch via bump2version (updates VERSION, commits, and tags)
          bump2version --allow-dirty patch

          # 3) Capture the newly created tag (e.g. v0.0.7)
          NEW_TAG=$(git describe --tags --abbrev=0)
          echo "Bumped to $NEW_TAG"
          echo "::set-output name=new_version::$NEW_TAG"

      - name: Push commit + tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD:main --follow-tags

  build:
    name: Build & Push Docker Image
    needs: version
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.version.outputs.new_version }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & push images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ needs.version.outputs.new_version }}
            ${{ env.IMAGE_NAME }}:latest

  deploy:
    name: SSH & Rollout to K3s
    needs: [version, build]
    runs-on: ubuntu-latest
    steps:
      - name: SSH to K3s and update deployment
        uses: appleboy/ssh-action@v1.0.0
        with:
          host:     ${{ secrets.K3S_SERVER_IP }}
          username: ${{ secrets.K3S_SERVER_USER }}
          key:      ${{ secrets.K3S_SSH_PRIVATE_KEY }}
          script: |
            TAG=${{ needs.version.outputs.new_version }}
            echo "Deploying image tag: ${TAG}"
            kubectl set image deployment/jhdev-website \
              jhdev-website=${{ env.IMAGE_NAME }}:${TAG} \
              -n jhdev
            kubectl rollout status deployment/jhdev-website \
              -n jhdev --timeout=300s
            echo "Deployment successful!"