# .github/workflows/deploy-manual.yml
name: 🚀 Deploy Specific Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Which Docker tag to deploy (e.g. v1.2.3)'
        required: true

permissions:
  contents: read

env:
  IMAGE_NAME: jhunter7/jhdev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH & Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host:     ${{ secrets.K3S_SERVER_IP }}
          username: ${{ secrets.K3S_SERVER_USER }}
          key:      ${{ secrets.K3S_SSH_PRIVATE_KEY }}
          script: |
            TAG=${{ github.event.inputs.tag }}
            echo "Deploying tag: $TAG"
            kubectl set image deployment/jhdev-website \
              jhdev-website=${IMAGE_NAME}:${TAG} -n jhdev
            kubectl rollout status deployment/jhdev-website \
              -n jhdev --timeout=300s
