# .github/workflows/ci-deploy.yml
name: 🚀 CI • Build & Deploy on Tag

on:
  push:
    tags:
      - 'v*'
  create:
    tags:
      - 'v*'

permissions:
  contents: read

env:
  IMAGE_NAME: jhunter7/jhdev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code at tag
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}  # uses the tag name, e.g. v1.2.3

      - name: SSH to K3s & rollout
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.K3S_SERVER_IP }}
          username: ${{ secrets.K3S_SERVER_USER }}
          key: ${{ secrets.K3S_SSH_PRIVATE_KEY }}
          script: |
            set -euo pipefail
            echo "Deploying image tag: ${{ github.ref_name }}"
            kubectl set image deployment/jhdev-website \
              jhdev-website=${{ env.IMAGE_NAME }}:${{ github.ref_name }} \
              -n jhdev
            kubectl rollout status deployment/jhdev-website -n jhdev --timeout=360s
